def retornar_dados_login(cpf):
    dados = {
        "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS1iZXR2aXAtYmV0YnIuYnMyYmV0LmNvbS92Mi9hdXRoL2xvZ2luIiwiaWF0IjoxNzQ5MjM1OTE5LCJleHAiOjE3NDk4NDA3MTksIm5iZiI6MTc0OTIzNTkxOSwianRpIjoiajNsczZrckJQdnYwalIxVSIsInN1YiI6IjQ4NzE4NiIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJoYSI6IjQiLCJoYiI6Ijc0MzE0NjRiN2JkYTQ1MGUwNjM4NGQzOGNlN2IwYWI2IiwiaGMiOiJiM2M4MzJiMzBlYjZhYTE4ODdjMjUwNjM5YzNlZGZkZCJ9.XXwSTnu5V27IlEJdTJ9WEzLYfvlLiV7OivhkxQPxSPw",
        "token_type": "bearer",
        "expires_in": 604800,
        "user": {
            "id": 487186,
            "name": "ITALO RAMON MATOS SILVEIRA",
            "email": "italomatos@live.com",
            "username": "750346f020688b5682bfcb185fafd2e7",
            "email_verified_at": None,
            "token": "betvip_-6xxk5Aoy2UzWvKa9GxKbLSQPv8jBZcXKETe5YxceOp0LGsByfPzYArX8R0g2TX",
            "ftd_value": 1,
            "ftd_date": "2024-02-23 15:51:31",
            "created_at": "2024-02-23T18:50:04.000000Z",
            "updated_at": "2025-06-06T18:51:59.000000Z",
            "is_active": 1,
            "phone": "85999983777",
            "commission": None,
            "manager_id": None,
            "admin_id": None,
            "commission_grid_id": None,
            "affiliation_code": "227c81c989ee",
            "recommended_by": None,
            "menu_list": None,
            "bonus_enabled": 0,
            "first_name": "ITALO",
            "last_name": "SILVEIRA",
            "mother_name": "",
            "gender": 2,
            "birth_date": "1993-04-23",
            "cancelled_account": 0,
            "is_test": 0,
            "ddi": "+55",
            "country": "BRA",
            "currency": "BRL",
            "language": "pt-br",
            "timezone": "America/Fortaleza",
            "address": "Campo Grande, 86, Ap 103 - Maraponga",
            "city": "Fortaleza",
            "state": "CE",
            "zipcode": "60711200",
            "is_internal": 0,
            "app_source": "migration_ganhabet",
            "roles": [
            {
                "id": 5,
                "name": "player",
                "guard_name": "api",
                "created_at": "2023-10-02T22:40:56.000000Z",
                "updated_at": "2023-10-02T22:40:56.000000Z",
                "pivot": {
                "model_id": 487186,
                "role_id": 5,
                "model_type": "App\\Models\\User"
                }
            }
            ],
            "document": {
            "id": 486674,
            "type": "cpf",
            "number": cpf,
            "user_id": 487186,
            "created_at": "2024-02-23T18:50:04.000000Z",
            "updated_at": "2024-02-23T18:50:04.000000Z"
            }
        },
        "userInfo": {
            "user_id": 487186,
            "tc_accepted_at": "2024-02-23 15:50:04",
            "mkt_accepted_at": "2024-02-23 15:50:04",
            "lgpd_accepted_at": "2024-02-23 15:50:04",
            "law_accepted_at": "2024-02-23 15:50:04",
            "migrate_accepted_at": "2024-02-23 15:50:04",
            "privacy_accepted_at": "2024-02-23 15:50:04",
            "status": 1,
            "status_updated_at": "2024-02-23 15:50:04",
            "status_note": None,
            "user_pause": 0,
            "user_pause_at": None,
            "user_exclusion": 0,
            "user_exclusion_at": None,
            "spa_exclusion": 0,
            "spa_exclusion_at": None,
            "spa_exclusion_note": None,
            "operator_exclusion": 0,
            "operator_exclusion_at": None,
            "operator_exclusion_note": None,
            "operator_exclusion_by": None,
            "user_limit_period": None,
            "user_limit_time": None,
            "user_limit_time_active": 0,
            "user_limit_time_period": None,
            "user_limit_time_change": None,
            "user_limit_bet": None,
            "user_limit_bet_active": 0,
            "user_limit_bet_period": None,
            "user_limit_bet_change": None,
            "user_limit_loss": None,
            "user_limit_loss_active": 0,
            "user_limit_loss_period": None,
            "user_limit_loss_change": None,
            "user_limit_deposit": None,
            "user_limit_deposit_active": 0,
            "user_limit_deposit_period": None,
            "user_limit_deposit_change": None,
            "user_limit_withdrawal": None,
            "user_limit_last_change": None,
            "last_verification_at": None,
            "login_at": "2025-06-06 15:51:59",
            "login_attempt_qty": 0,
            "login_city": "Fortaleza",
            "login_state": "CE",
            "login_ip": "2804:29b8:50f4:bd96:7cda:d144:9ac8:684b",
            "validate_email_at": None,
            "validate_sms_at": None,
            "kyc_validated_at": "2025-02-16 04:55:57",
            "latitude": "-3.71722",
            "longitude": "-38.54306",
            "strong_password": 0,
            "location_at": None,
            "nationalities": "[{\"id\": 1, \"value\": \"Brasileiro (a)\"}]",
            "created_at": "2025-01-31T05:14:28.000000Z",
            "updated_at": "2025-06-06T18:51:59.000000Z",
            "id": 968918,
            "two_factor_enabled": 0,
            "two_factor_type": None,
            "two_factor_at": None,
            "login_device":None
        }
        }